config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :home
  resources :contacts
  resources :film
  resources :code
  resources :comments

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/code_controller.rb
class CodeController < ApplicationController

  def index
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/code/index.html.erb
<div class= 'code-container'>

  <div class= 'code-nav'>
      <%= link_to 'home', home_index_url %> |
      <%= link_to 'film', film_index_url %> |
      <%= link_to 'contact', contacts_url %>
  </div>      

  <div class= 'aniComputer'>
    <%= image_tag 'horse.png', class: 'pony' %>
  </div>

   <!-- INSERT PROJECTS -->
      <h2>Skills</h2>
        <div class="skills">
            <p class= 'skillcont'>
              Ruby<span> | </span>
              Rails<span> | </span>
              Javascript<span> | </span>
              HTML<span> | </span>
              CSS<span> | </span>
              SQL<span> | </span>
              Postgresql<span> | </span>
              Slack
            </p>
        </div>

        <h2>Education</h2>
        <div class="education">
            <p class="edu"> DEV Bootcamp - Full Stack Development, 2016</p>
        </div>

</div>

app/views/comments/_form.html.erb
<%=  form_for :comment, url: '/comments' do |f| %>

  <%= f.text_field :comment, placeholder: 'Message:', class: 'msg-field' %><br>
  <%= f.text_field :user, placeholder: 'From:', class: 'name-field' %><br>
  <%= submit_tag 'leave a note' %>

<% end %>

app/views/film/index.html.erb
<div class= 'film-container'>

<div class= 'film-nav'>
    <%= link_to 'home', home_index_url %> |
    <%= link_to 'code', code_index_url %> |
    <%= link_to 'contact', contacts_url %>
</div>

<div class= 'aniKen'>
  <%= image_tag '/images/kenjamin.png', class: 'kenjamin' %>
</div>


<div class="experience">
          <table border=1>
            <tr>
              <th>Position</th>
              <th>Project</th>
              <th>Type</th>
              <th>Producer</th>
              <th>Director</th>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td><i>Souvenirs</i></td>
              <td>Short</td>
              <td>Anthony Ojo</td>
              <td>Anthony Ojo</td>
            </tr>
            <tr>
              <td>Set Carpenter</td>
              <td><i>Robo-Dog 2</i></td>
              <td>Feature</td>
              <td>Mark Boot</td>
              <td>Jason Murphy</td>
            </tr>
            <tr>
              <td>Unit Production Manager</td>
              <td><i>November 30th</i></td>
              <td>Short</td>
              <td>Larry Katz</td>
              <td>Nathan Wind</td>
            </tr>
            <tr>
              <td>Casting Secretary</td>
              <td><i>November 30th</i></td>
              <td>Short</td>
              <td>Larry Katz</td>
              <td>Nathan Wind</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td>January May <i>Young</i></td>
              <td>Music Video</td>
              <td>Nestor Vera</td>
              <td>Deion McCarter</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td><i>Table Manners</i></td>
              <td>Short</td>
              <td>Jason Boyette</td>
              <td>Michelle Navarrete</td>
            </tr>
            <tr>
              <td>Casting Secretary</td>
              <td><i>Table Manners</i></td>
              <td>Short</td>
              <td>Jason Boyette</td>
              <td>Michelle Navarrete</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td>IYAZ <i>Sleeping Along</i></td>
              <td>Music Video</td>
              <td>Mohsen Khaial</td>
              <td>Carl Verna</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td><i>Amber Eyes</i></td>
              <td>Short</td>
              <td>Steven Astacio</td>
              <td>Angelo Isnardi</td>
            </tr>
            <tr>
              <td>1st Assistant Director</td>
              <td>Full Sail BTS Tour</td>
              <td>Live Production</td>
              <td>Duane More</td>
              <td>Rob Haynes</td>
            </tr>
            <tr>
              <td>Director</td>
              <td><i>The Weekend</i></td>
              <td>Television</td>
              <td>Katelyn Gelhart</td>
              <td>Sierra McLawhorn</td>
            </tr>
            <tr>
              <td>Production Manager</td>
              <td><i>Shazam!</i></td>
              <td>Documentary</td>
              <td>Dean McDermitt</td>
              <td>Heath Neptune</td>
            </tr>
            <tr>
              <td>Script Supervisor/BTS</td>
              <td><i>Hoop Culture</i></td>
              <td>Web Promo Series</td>
              <td>David Daudin</td>
              <td>Christopher Gotera</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td><i>Waiting</i></td>
              <td>Short</td>
              <td>Sam Duzansky</td>
              <td>Heath Neptune</td>
            </tr>
            <tr>
              <td>Casting Director</td>
              <td><i>Waiting</i></td>
              <td>Short</td>
              <td>Sam Duzansky</td>
              <td>Heath Neptune</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td>Doritos: <i>Poker Chips</i></td>
              <td>Commercial</td>
              <td>Sam Duzansky</td>
              <td>Pedro Morales</td>
            </tr>
             <tr>
              <td>Videographer</td>
              <td><i>15th World Congress</i></td>
              <td>Live Stream</td>
              <td>Effie Chow</td>
              <td>Effie Chow</td>
            </tr>
          </table>
          
          <p>Currently interning as an Assistant Producer for <i>The Culture Trip</i> 's documentary web series based in the San Francisco Bay Area.</p>
        </div>


        <h2>Skills</h2>
        <div class="skills">
            <p class= 'skillcont'>
              Avid Media Composer<span> | </span>
              Final Cut Pro X<span> | </span>
              Vectorworks<span> | </span>
              Adobe Lightroom<span> | </span>
              Microsoft Office<span> | </span>
              Adobe Reader<span> | </span>
              Vimeo<span> | </span>
              Youtube<span> | </span>
              Basecamp
            </p>
        </div>

        
        <h2>Education</h2>
        <div class="education">
            <p class="edu">Full Sail University - Film B.S., 2015</p>
            <p class="edu" id="edusub">Creative Minds Scholarship recipient</p>
        </div>

    

app/views/home/_about.html.erb
<div class="harlotContainer">  
  <%= render 'harlot' %>
</div>

<div class="infoAboutContainer">
  <%= render 'aboutinfo' %>
</div>

app/views/home/_code.html.erb
<div class= 'code-container'>

  <div class= 'aniComputer'>
    <%= image_tag 'horse.png', class: 'pony' %>
  </div>

   <!-- INSERT PROJECTS THE POPUP AS MOGLES -->
      <h2>Skills</h2>
        <div class="skills">
            <p class= 'skillcont'>
              Ruby<span> | </span>
              Rails<span> | </span>
              Javascript<span> | </span>
              HTML<span> | </span>
              CSS<span> | </span>
              SQL<span> | </span>
              Postgresql<span> | </span>
              Slack
            </p>
        </div>

        <h2>Education</h2>
        <div class="education">
            <p class="edu"> DEV Bootcamp - Full Stack Development, 2016</p>
        </div>

</div>

app/views/home/_contact.html.erb
  <div class= 'contact'>
  <%= image_tag 'harlotcontact.png', class: 'contact-img' %>
  </div>

app/views/home/_film.html.erb
<div class= 'film-container'>

<div class="experience">
          <table border=1>
            <tr>
              <th>Position</th>
              <th>Project</th>
              <th>Type</th>
              <th>Producer</th>
              <th>Director</th>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td><i>Souvenirs</i></td>
              <td>Short</td>
              <td>Anthony Ojo</td>
              <td>Anthony Ojo</td>
            </tr>
            <tr>
              <td>Set Carpenter</td>
              <td><i>Robo-Dog 2</i></td>
              <td>Feature</td>
              <td>Mark Boot</td>
              <td>Jason Murphy</td>
            </tr>
            <tr>
              <td>Unit Production Manager</td>
              <td><i>November 30th</i></td>
              <td>Short</td>
              <td>Larry Katz</td>
              <td>Nathan Wind</td>
            </tr>
            <tr>
              <td>Casting Secretary</td>
              <td><i>November 30th</i></td>
              <td>Short</td>
              <td>Larry Katz</td>
              <td>Nathan Wind</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td>January May <i>Young</i></td>
              <td>Music Video</td>
              <td>Nestor Vera</td>
              <td>Deion McCarter</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td><i>Table Manners</i></td>
              <td>Short</td>
              <td>Jason Boyette</td>
              <td>Michelle Navarrete</td>
            </tr>
            <tr>
              <td>Casting Secretary</td>
              <td><i>Table Manners</i></td>
              <td>Short</td>
              <td>Jason Boyette</td>
              <td>Michelle Navarrete</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td>IYAZ <i>Sleeping Along</i></td>
              <td>Music Video</td>
              <td>Mohsen Khaial</td>
              <td>Carl Verna</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td><i>Amber Eyes</i></td>
              <td>Short</td>
              <td>Steven Astacio</td>
              <td>Angelo Isnardi</td>
            </tr>
            <tr>
              <td>1st Assistant Director</td>
              <td>Full Sail BTS Tour</td>
              <td>Live Production</td>
              <td>Duane More</td>
              <td>Rob Haynes</td>
            </tr>
            <tr>
              <td>Director</td>
              <td><i>The Weekend</i></td>
              <td>Television</td>
              <td>Katelyn Gelhart</td>
              <td>Sierra McLawhorn</td>
            </tr>
            <tr>
              <td>Production Manager</td>
              <td><i>Shazam!</i></td>
              <td>Documentary</td>
              <td>Dean McDermitt</td>
              <td>Heath Neptune</td>
            </tr>
            <tr>
              <td>Script Supervisor/BTS</td>
              <td><i>Hoop Culture</i></td>
              <td>Web Promo Series</td>
              <td>David Daudin</td>
              <td>Christopher Gotera</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td><i>Waiting</i></td>
              <td>Short</td>
              <td>Sam Duzansky</td>
              <td>Heath Neptune</td>
            </tr>
            <tr>
              <td>Casting Director</td>
              <td><i>Waiting</i></td>
              <td>Short</td>
              <td>Sam Duzansky</td>
              <td>Heath Neptune</td>
            </tr>
            <tr>
              <td>Script Supervisor</td>
              <td>Doritos: <i>Poker Chips</i></td>
              <td>Commercial</td>
              <td>Sam Duzansky</td>
              <td>Pedro Morales</td>
            </tr>
             <tr>
              <td>Videographer</td>
              <td><i>15th World Congress</i></td>
              <td>Live Stream</td>
              <td>Effie Chow</td>
              <td>Effie Chow</td>
            </tr>
          </table>
          
          <p>Currently interning as an Assistant Producer for <i>The Culture Trip</i> 's documentary web series based in the San Francisco Bay Area.</p>
        </div>


        <h2>Skills</h2>
        <div class="skills">
            <p class= 'skillcont'>
              Avid Media Composer<span> | </span>
              Final Cut Pro X<span> | </span>
              Vectorworks<span> | </span>
              Adobe Lightroom<span> | </span>
              Microsoft Office<span> | </span>
              Adobe Reader<span> | </span>
              Vimeo<span> | </span>
              Youtube<span> | </span>
              Basecamp
            </p>
        </div>

        
        <h2>Education</h2>
        <div class="education">
            <p class="edu">Full Sail University - Film B.S., 2015</p>
            <p class="edu" id="edusub">Creative Minds Scholarship recipient</p>
        </div>

</div>

app/views/home/_harlot.html.erb
<svg class="harlotSVG" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 414 468" enable-background="new 0 0 414 468" xml:space="preserve">
  <path class="harlotpath" fill="none" stroke="#000000" stroke-miterlimit="10" d="M124,826c7-1,15,1,20,7c-14,24-4,65-44,63c-37-3-11-45-23-68
  c-13-25-33-31-35-63c-2.239-26.874,3.329-56.796,12.299-82.024c4.831-13.586,13.719-22.056,20.24-33.903
  c8.449-15.352-0.175-45.902-2.513-62.873c-2.293-16.644-9.859-73.973,4.799-84.249c1.511-25.305,7.569-49.742,10.178-74.027
  c1.926-17.928,12.703-39.022,11.04-56.777c-0.983-10.49-8.535-18.396-11.313-28.149c-2.3-8.076-0.045-16.549-2.781-24.872
  c-4.346-13.22-15.822-22.374-14.997-38.822c2.26,5.182,6.303,10.827,11.897,11.562c1.007-6.059-2.272-11.504-1.917-17.61
  c2.208,3.83,6.618,5.295,10.953,4.636c-1.459-7.212-3.894-14.366-4.837-21.787c1.608-0.013,3.25-0.308,4.879-0.103
  c-3.795,0.461-7.489-0.476-10.769-2.171c0.292-5.884,9.799-6.085,13.894-10.826c4.645-5.378,3.861-8.303,3.993-15.724
  c-3.42,8.21-11.064,9.281-17.143,14.721c-4.196,3.755-3.822,8.175-9.528,10.698c-1.441-6.322,3.787-17.931,5.714-24.435
  c-3.583,5.289-10.324,11.117-11.084,17.454c-0.619-9.288,1.116-18.531,7.048-25.577c-4.166-0.196-6.679,2.844-8.104,6.544
  c0.155-10.52-2.187-20.625,6.995-27.331c-7.728,4.914-18.92,15.567-21.002,24.408c1.132-11.168,14.87-19.134,18.931-28.587
  c-13.545,1.848-15.102-12.005-4.651-16.171c-12.727,0.19-13.815,5.03-24.379,10.586c2.168-14.224,15.762-16,19.381-26.39
  c3.604-10.35-2.742-36.415-8.297-44.525c0.415-3.725-3.671-14.159-3.925-20.651c-0.345-8.831-0.706-16.443-2.726-24.301
  C41.69,63.673,35.685,31.138,51,29 M348.969,365c2-11,18.969-44,11.969-49c2-6,6.938-12,6.938-18c-2-1-4.125-2-6.125-2
  c4-9,14.75-27-0.25-30c0,1,0,1,0,2c15-14,0.25-21-11.75-16c22-7-20.75-24,11.25-26c-6-1-11-3-14-8c1,0,5-2,7-2c-6-4-11-10-10-17
  c17,1,28,16,33,30c-5-15-4-29-22-36c12,4,18,5,28,13c-1-11-12-15-16-25c3,1,9-1,10-1c-3-1-7-4-10-6c2,1,5,0,7,0c-2-2-5-8-7-10
  c9-9,12-35,16-47c5-15-1-30,0-46c0-14,5-45-7-56c-20-17-73,50-88,63c-2,0-2-2-3-3c-1,3-3,5-4,8c0-5-2-11-2-15c-3,6-5,14-8,21
  c0-4-2-8-2-12c-4,11-3,27-7,36c-8,17-47,15-64,17c-8,1-27,7-34,1c-9-8,1-26-2-37c-3,4-4,4-5,9c3-9,4-22-2-30c0,7-2,14-2,21
  c-2-4-5-5-7-8c0,3-1,6-1,9c-9-5-13-16-21-22c-9-7-20-12-29-20C82,43,68,29,50,29 M127,393c5,6,12,10,19,12c-2-3-3-7-5-10
  c5,8,12,17,20,22c-1-7-3-13-4-20c-1,14,6,32,20,34c0-3,0-8-2-11c5,9,15,13,24,15c-1-2-3-8-4-11c6,6,14,11,22,12c0-2,2-5,2-7
  c3,5,7,8,13,10c0-3,3-7,4-10c4,2,7,7,8,13c-1-3,0-7,0-9c5,0,10,2,15,4c-3-7-8-14-9-22c4,7,11,12,18,15c2-5,2-11,2-17
  c9,16,10,17,23,2c0,2,1,4,1,6c7-3,11-10,11-18c1,1,3,4,4,6c4-7,7-16,8-25c1,4,6,9,7,12c4-5,6-11,8-17 M71,288c7,13,35,30,50,27
  c2-12-10-26-5-36c3,8-1,19,7,25c9-8,3-32,5-44c3-13,4-9,1-22c-2-10-5-17-4-28c1-13,4-13,13-23c1-1,8-3,9-5c1-6-6-6-6-9
  c1-11,11-35,27-37 M84,185c9-6,18-8,28-11c-2-2-3-4-4-6c5-3,11-5,16-8c-6-4-13-4-20-4c5-4,12-4,18-4c-2-2-5-6-7-7c2,0,4-2,6-2
  c-1-2-1-6-3-8c4,0,9-2,12-2c0-3-1-7-2-9c1-2,2,0,3-2c-9-19-66-92-89-80 M356,54c-1,1-8,5-11,6c3,2,6,8,10,9c-9,3-19,3-25,11
  c4,0,10,1,14,0c-11,3-24,7-27,18c-1,1,3,1,3,1c-2,1-5,3-7,4c6-2,13-4,19-4c-7,6-14,12-20,19c4-1,9-1,12-2c-4,8-9,16-10,25
  c1-2,4-3,5-4c8,13,1,19,17,29 M194,132c16,7,48-8,44,13c-2,11-8,16-8,27c0,7,8,19-9,18c-7,17,2,27,12,39s17,19,29,27
  c31,21,18,42,11,72c12-1,26-7,34,4c7,9,3,26,11,36c7-6,9-23,19-21c1-5,1-11,2-16c2,2,7,4.25,9,6.25c1-7,1-12.75,1-19.75c2,0,4,0,5,0
  c0-4,1-7.25-1-11.25c6-3,7-19.125,15-26.125 M310,250c-14,5-4,19-4,28c0,5-9,31-1,28c1-1,16-23,17-26c5-12-2-19-11-28 M163,282
  c-3,4-4,8-2,13c21-5,20,18,1,9c0,7,14,21,22,17c9-3,4-17,4-25c1,9,0,19,3,27c10,1,19-7,22-16c-31,2-4-31,2-5c16-5-2-25-11-28
  c-14-5-27,2-39,7 M234,337c-1,8,3,16,2,23c-2,8-9,11-6,20c10-8,20-26,26-38c5-12,16-32,17-44c-13,12-21,33-37,39c-15,6-35,0-46-11
  c-9,14-32,18-45,5 M164,342c1,15,3,45,16,53c15,9,44,2,49-16 M202,350c-1,18-8,34-7,52 M181,342c-12,17-15,38,1,54 M239,214
  c6,3.5,12,8,19.5,8c15.5,0.5,31.5-20,12-28c-7.462-3.062-19.47-0.36-22.426,8.114c-4.038,11.577,14.224,7.974,10.568-0.396
  c-4.391-10.05-10.425,4.814-9.585,9.556c1.659,9.369,13.755,11.522,19.056,4.337c4.162-5.644,6.175-12.162-1.363-17.109
  c-13.495-8.856-23.361,3.833-28.25,14.498 M165.5,215c-5.196-7.274-16.572-19.79-26.613-12.358c-2.906,2.151-6.324,9.5-5.455,13.015
  c1.031,4.171,8.144,8.606,12.567,8.843c20.785,1.112,11.435-33.074-2.67-18.514c-3.322,3.429-1.656,12.743,4.075,9.25
  c5.311-3.235,0.345-8.865-3.363-10.087c-14.204-4.682-19.675,15.187-8.225,22.014c10.238,6.105,24.796-5.468,32.683-11.164"/>
</svg>

app/views/home/_potato.html.erb
<div class= 'potato-container'>

  <div class= 'aniPotato'>
     <%= link_to image_tag('potato.png', class: 'potato'), home_index_url %> 
  </div>

</div>

app/views/home/index.html.erb
<div class= 'home-container'>

  <div class= 'body'>

    <%= render 'about' %>

    <div class="linkedInfo">
      <%= render 'potato' %>
      <%= render 'film' %>
      <%= render 'code' %>
      <%= render 'contact' %>
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sierramclawhorn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>